version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: springbooot-app
#    restart: always
    build: .
    ports:
      - 8000-8999:8080
    networks:
      - employee-mysql
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: Rahul@123
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    networks:
      - employee-mysql
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root

networks:
  employee-mysql: