#server:
#  port: 2022
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/MentorsDB
#    username: root
#    password: Rahul@123
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true